name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "VITE_FIREBASE_RTBD_URL=${{ vars.VITE_FIREBASE_RTDB_URL }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ vars.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ vars.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ vars.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env

      - name: Debug Environment Variables
        run: cat .env
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLDEN_ANTELOPE }}
          channelId: live
          projectId: golden-antelope
          target: stage
